name: jci
description: Powered by nutz

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  url_launcher: ^6.0.12
  http: ^0.13.3
  photo_view: ^0.13.0
  syncfusion_flutter_calendar: ^19.3.44
  page_transition: ^2.0.4
  get: ^4.1.4
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0
  hexcolor: ^2.0.5
  flutter_dotenv: ^5.0.2
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  firebase_dynamic_links: ^3.0.1
  lottie: ^1.2.1
  flutter_local_notifications: ^8.1.0
  open_file: ^3.2.1
  flowder: ^0.2.0
  path_provider: ^2.0.6
  permission_handler: ^8.2.5
  app_settings: ^4.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
dev_dependencies:

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
   - assets/images/
   - assets/lottie/
   - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: pop-reg
     fonts:
       - asset: fonts/Poppins-Regular.ttf
   - family: pop-med
     fonts:
       - asset: fonts/Poppins-Medium.ttf
   - family: pop-semibold
     fonts:
       - asset: fonts/Poppins-SemiBold.ttf
   - family: pop-bold
     fonts:
       - asset: fonts/Poppins-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
